### ISSUE TITLE
HOW TO BUILD

### ISSUE THREAD

**Issue by shadowelite-sec** [System64fumo/sysvol#2]
hey what are the requirements need to build ?

i tried using aur pkg but its failed to build

https://aur.archlinux.org/packages/sysvol

i think something wrong with gtk4-layer-shell

**Comment by System64fumo** [comment]
Hello, Sorry for the late response
The base build requirements are gtkmm-4.0 and gtk4-layer-shell
And depending on if you have pulse or wireplumber on your system
The appropiate dependency will be selected

Since you haven't provided any logs or specific issue i'm going to assume it's related to [this](https://github.com/System64fumo/sysmenu/issues/1)

Please try reinstalling gtk4-layer-shell or provide me with the build logs

**Comment by shadowelite-sec** [comment]
i fixed it by commenting PKGBUILD c
heck of gtk4-layer-shell
